### ISSUE TITLE
Delete users with existing Sierra accounts who logged on for the first time before 8 September 2021

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/identity#181]
There is a fix for users logging in with existing accounts in Sierra such that they are marked as verified (#174 ), which was closed on 7 September.

This does not help people who logged in before that fix was made (7 September): they still see the message that their email isn't validated on their account page.

For the small number of affected users, we can fix it by deleting their Auth0 accounts (this should have no adverse affects as their Sierra accounts will just be re-imported). ([comment](https://github.com/wellcomecollection/identity/issues/174#issuecomment-915132665))

**Comment by alexwlchan** [comment]
This is done.

I've reviewed the list of users in both prod and stage; there are no external users who first logged in before 8th September. Either nobody logged in before then, or somebody has already sorted this.

There are some staff users, but deleting those accounts is a bunch of point-and-clicking that's probably unnecessary.
