### ISSUE TITLE
User deletion fails with 'unknown error'

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/identity#195]
The API response is:

```
ENOENT: Failed to lookup \"delete-request_admin_subject\" in \"/var/task/utils/templates\"
```

So it's something to do with email templates.

Steps to reproduce:
1. Log in and go to account page
2. Request deletion
3. See error

**Comment by gestchild** [comment]
Templates are now being deployed (wellcomecollection/identity#205) but [the deletion request times out ](https://wellcome.slack.com/archives/C294K7D5M/p1636037416064900?thread_ts=1636025117.056900&cid=C294K7D5M)

**Comment by gestchild** [comment]
Closing this as the original issue is fixed.
Have opened a new one, #206, for the issue we are seeing on stage
