### ISSUE TITLE
Deletion request failing on stage

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/identity#206]
The functionality works fine on prod, just not on stage so is likely related to mailtrap configuration.

To replicate the error:
- go to www-stage.wellcomecollection.org log into your account
- go to the account page and scroll to the bottom
- click 'cancel your membership'
- enter your password in the modal and click 'yes, delete my account'
- It will eventually error. If you look in the network tab of dev tools you'll see a response code of 504 Gateway timeout.

**Comment by jamieparkinson** [comment]
This was resolved by changing the port from `25`, which is blocked in AWS
