### ISSUE TITLE
Restricted items access for staff

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/identity#402]
Staff need to be able to access restricted items. Currently there is no provision for viewing restricted items via the catalogue, even where staff are logged in. 

Notion link: https://www.notion.so/wellcometrust/Restricted-items-access-for-staff-bc55baf9a896490d956666515958d2a5?pvs=4

**Comment by kenoir** [comment]
Replaced by https://github.com/wellcomecollection/platform/issues/5747
